kind: Deployment
apiVersion: apps/v1
metadata:
    generation: 1
    labels:
        app: xpctl-server
    name: xpctl-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: xpctl-server
    template:
        metadata:
            labels:
                app: xpctl-server
        spec:
            containers:
                - name: xpctl-server-mongo
                  image: eu.gcr.io/bubbly-monument-292720/xpctl-server-mongo:latest
                  imagePullPolicy: Always
                  command:
                    - python
                    - -m
                    - xpserver
                  args:
                      - --backend=mongo
                      - --cred=./xpctlcred.yaml
                      - --port=8080
                  ports:
                      - containerPort: 8080
                  env:
                      - name: PORT
                        value: "8080"      
