kind: Service
apiVersion: v1
metadata:
  labels:
    app: xpctl-server
  name: xpctl-server
spec:
  type: LoadBalancer
  selector:
    app: xpctl-server
  ports:
    - port: 80
      targetPort: 8080
